<div id="project_item_[field:global.autoindex/]" class="item_block wow" style="animation-delay:.[field:global.autoindex/]s"> <a href="[field:arcurl/]" class="item_link clearfix" target="_blank">
                <div class="item_img"> <img src="[field:picname/]" alt="[field:title/]" />
                  <div class="item_mask"></div>
                </div>
                <div class="item_wrapper">
                  <div class="item_info">
                    <p class="nums ellipsis">0[field:global.autoindex/]</p>
                    <p class="title ellipsis">[field:title/]</p>
                    <p class="line"></p>
                    <p class="subtitle ellipsis">[field:description/]...</p>
                    <p class="details"><i class="fa fa-ico01" aria-hidden="true"></i></p>
                  </div>
                </div>
                </a> </div>