<div id="item_block_[field:global.autoindex/]" class="item_block wow"> <a href="view.php?aid=[field:id/]" class="item_link clearfix">
                <div href="view.php?aid=[field:id/]" class="item_img" target="_blank">
                  <p class="img_box"><img src="[field:picname/]" alt="[field:title/]" /></p>
                </div>
                <div class="item_wrapper clearfix">
                  <div class="item_info clearfix">
                    <p class="title ellipsis">[field:title/]</p>
                    <div class="description">
                      <p>[field:description/]...</p>
                    </div>
                    <p class="details"><i class="fa fa-ico01" aria-hidden="true"></i></p>
                  </div>
                </div>
                </a> </div>