<div class="item_block">
            <div class="item_bg image" data-thumb="[field:picname/]" style="background-image:url([field:picname/])"></div>
            <a target="_blank" href="[field:redirecturl/]" style="width: 100%; height: 100%;">
            <div class="description" style="vertical-align:middle; text-align:center">
              <p class="title ellipsis">[field:title/]</p>
              <p class="subtitle">[field:description/]</p>
            </div>
            </a> </div>