<div id="project_item_[field:global name=autoindex runphp='yes']@me=@me-1;[/field:global]" class="item_block wow" style="animation-delay:.[field:global.autoindex/]s"> <a href="[field:video/]" class="item_link clearfix" target="_blank">
                  <div class="item_img"> <img src="[field:picname/]" alt="[field:title/]" />
                    <div class="item_mask"></div>
                    <div class="item_ico"> </div>
                  </div>
                  <div class="item_wrapper">
                    <div class="item_info">
                      <p class="title ellipsis">[field:title/]</p>
                      <p class="subtitle ellipsis">[field:shorttitle/]</p>
                    </div>
                  </div>
                  </a> </div>