<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]=array();
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/181205/1-1Q205163413.jpg ",93,239);
$z[1][4]=array();
$z[1][4]['ddimg']="/uploads/allimg/181205/1-1Q205163413.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="1920";
$z[1][4]['height']="540";
$z[2]=Array("img"," /uploads/allimg/181205/1-1Q205163414.jpg ",241,387);
$z[2][4]=array();
$z[2][4]['ddimg']="/uploads/allimg/181205/1-1Q205163414.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="1920";
$z[2][4]['height']="540";

?>