<?php
$z[0]=Array("pagestyle","",0,90);
$z[0][4]=array();
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="1";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="1";
$z[1]=Array("img"," /uploads/allimg/190408/1-1Z40Q34257.jpg ",92,242);
$z[1][4]=array();
$z[1][4]['ddimg']="/uploads/allimg/190408/1-1Z40Q34257.jpg";
$z[1][4]['text']="头图";
$z[1][4]['width']="1920";
$z[1][4]['height']="540";

?>