<?php
$z[0]=Array("global","",19,44);
$z[0][4]=array();
$z[0][4]['name']="autoindex";
$z[1]=Array("global","(@me%2==0)? @me=\"\":@me=\"first\";",68,156);
$z[1][4]=array();
$z[1][4]['name']="autoindex";
$z[1][4]['runphp']="yes";
$z[2]=Array("global","",182,207);
$z[2][4]=array();
$z[2][4]['name']="autoindex";
$z[3]=Array("id","",233,244);
$z[3][4]=array();
$z[4]=Array("picname","",337,353);
$z[4][4]=array();
$z[5]=Array("title","",360,374);
$z[5][4]=array();
$z[6]=Array("title","",529,543);
$z[6][4]=array();
$z[7]=Array("description","",586,606);
$z[7][4]=array();

?>