<div class="mcustomize module bgShow bgParallax" style=" background-image:url([field:typebg/]);">
    <div class="bgmask"></div>
    <div class="module_container">
      <div class="container_content">
        <div class="contentbody">
          <div class="wrapper">
            <div class="header wow">
              <p class="title">[field:typename/]</p>
              <p class="subtitle">[field:typeeng/]</p>
            </div>
            <div class="description wow">
              <p>[field:description/]...</p>
              <p><br />
              </p>
              <p><a href="list.php?tid=14" target="_blank" class="more">查看更多</a><br />
              </p>
            </div>
          </div>
        </div>
        <div class="clear"></div>
      </div>
    </div>
  </div>