<div id="project_item_[field:global.autoindex/]" class="item_block wow" style="animation-delay:.[field:global.autoindex/]s"> <a href="view.php?aid=[field:id/]" class="item_link clearfix">
                <div class="item_img"> <img src="[field:picname/]" alt="[field:title/]" />
                  <div class="item_mask"></div>
                </div>
                <div class="item_wrapper">
                  <div class="item_info">
                    <p class="title ellipsis">[field:title/]</p>
                    <p class="line"></p>
                    <p class="subtitle ellipsis">[field:description/]...</p>
                  </div>
                </div>
                </a> </div>