<div id="item_block_[field:global.autoindex/]" class="item_block wow"> <a href="[field:arcurl/]" class="item_link clearfix">
                  <div href="[field:arcurl/]" class="item_img" target="_blank">
                    <p class="img_box"><img src="[field:picname/]" alt="[field:title/]" /></p>
                    <div class="description">
                      <p> 人物履历设计风格优雅而前卫，注重服装设计的原创精神。设计师将复古元素和现代简约设计巧妙的结合在一起，创造出一种精致并且经典的设计风格。设计师认为面料是影响服装设计的关键所在，运用有着独特的见解，而每一季由设计师亲自操刀设计的另类印花面料，更是品牌的一大特点，众多时装品牌中显得独一无二。价位适中、实穿性强却又不失个性则是设计主张。女性是独立自信和优雅的。对美的追求从来不受他人或外界影响，以自成一格的美学态度传递对时尚的热爱及影响。</p>
                    </div>
                  </div>
                  <div class="thumbnail"> <img src="[field:picname/]" alt="[field:title/]" /> </div>
                  <div class="item_wrapper clearfix">
                    <div class="item_info clearfix">
                      <p class="title ellipsis">[field:title/]</p>
                      <p class="subtitle ellipsis">[field:shorttitle/]</p>
                    </div>
                  </div>
                  <p class="line"></p>
                  </a> </div>