
    <m:item name='普通文章' ischannel='1' link='content_list.php?channelid=1' linkadd='article_add.php?channelid=1' channelid='1' rank='' target='main' />
  <m:item name='图片集' ischannel='1' link='content_i_list.php?channelid=2' linkadd='album_add.php?channelid=2' channelid='2' rank='' target='main' />
  <m:item name='幻灯片' ischannel='1' link='content_list.php?channelid=4' linkadd='article_add.php?channelid=4' channelid='4' rank='' target='main' />
  <m:item name='视频' ischannel='1' link='content_list.php?channelid=5' linkadd='article_add.php?channelid=5' channelid='5' rank='' target='main' />

  <m:item name='专题管理' ischannel='1' link='content_s_list.php' linkadd='spec_add.php' channelid='-1' rank='spec_New' target='main' />
