<?php
$z[0]=Array("global","",19,44);
$z[0][4]=array();
$z[0][4]['name']="autoindex";
$z[1]=Array("global","(@me%2==0)? @me=\"\":@me=\"first\";",68,156);
$z[1][4]=array();
$z[1][4]['name']="autoindex";
$z[1][4]['runphp']="yes";
$z[2]=Array("global","",182,207);
$z[2][4]=array();
$z[2][4]['name']="autoindex";
$z[3]=Array("arcurl","",220,235);
$z[3][4]=array();
$z[4]=Array("picname","",332,348);
$z[4][4]=array();
$z[5]=Array("title","",355,369);
$z[5][4]=array();
$z[6]=Array("global","",540,565);
$z[6][4]=array();
$z[6][4]['name']="autoindex";
$z[7]=Array("title","",616,630);
$z[7][4]=array();
$z[8]=Array("description","",677,697);
$z[8][4]=array();

?>