<div id="project_item_[field:global.autoindex/]" class="item_block" style="animation-delay:.[field:global.autoindex/]s"> <a href="[field:video/]" class="item_link clearfix">
              <div class="item_img">
                <p class="img_box"><img src="[field:picname/]" alt="[field:title/]" /></p>
                <div class="item_mask"></div>
                <div class="item_ico"></div>
              </div>
              <div class="item_wrapper clearfix">
                <div class="item_info clearfix">
                  <p class="title ellipsis">[field:title/]</p>
                  <div class="description">
                    <p>[field:shorttitle/]</p>
                  </div>
                </div>
              </div>
              </a> </div>