<li id="item_block_[field:global.autoindex/]" class='item_block wow [field:global name=autoindex runphp="yes"](@me%2==0)? @me="":@me="first";[/field:global]' style="animation-delay:.[field:global.autoindex/]s"> <a href="view.php?aid=[field:id/]" class="item_link clearfix" target="_blank">
                <div class="item_img"> <img src="[field:picname/]" alt="[field:title/]" />
                  <div class="item_mask"></div>
                </div>
                <div class="item_wrapper">
                  <p class="title ellipsis">[field:title/]</p>
                  <div class="subtitle">[field:description/]...</div>
                  <p class="detailsde"><i class="fa fa-ico01" aria-hidden="true"></i></p>
                </div>
                </a> </li>