<div id='item_block_[field:global name=autoindex runphp="yes"]@me=@me+1;[/field:global]' class="item_block wow"> <a href="[field:arcurl/]" class="item_link clearfix">
                <div href="[field:arcurl/]" class="item_img" target="_blank">
                  <p class="img_box"><img src="[field:picname/]" alt="[field:title/]" /></p>
                  <div class="description">
                    <p>[field:description/]...</p>
                  </div>
                </div>
                <div class="thumbnail"> <img src="[field:picname/]" alt="[field:title/]" /> </div>
                <div class="item_wrapper clearfix">
                  <div class="item_info clearfix">
                    <p class="title ellipsis">[field:title/]</p>
                    <p class="subtitle ellipsis">[field:shorttitle/]</p>
                  </div>
                </div>
                <p class="line"></p>
                </a> </div>