<?php
$z[0]=Array("global","",19,44);
$z[0][4]=array();
$z[0][4]['name']="autoindex";
$z[1]=Array("global","(@me%2==0)? @me=\"\":@me=\"first\";",68,156);
$z[1][4]=array();
$z[1][4]['name']="autoindex";
$z[1][4]['runphp']="yes";
$z[2]=Array("global","",182,207);
$z[2][4]=array();
$z[2][4]['name']="autoindex";
$z[3]=Array("arcurl","",220,235);
$z[3][4]=array();
$z[4]=Array("picname","",330,346);
$z[4][4]=array();
$z[5]=Array("title","",353,367);
$z[5][4]=array();
$z[6]=Array("global","",530,555);
$z[6][4]=array();
$z[6][4]['name']="autoindex";
$z[7]=Array("title","",604,618);
$z[7][4]=array();
$z[8]=Array("description","",663,683);
$z[8][4]=array();

?>