<div id="item_block_[field:global.autoindex/]" class="item_block wow"> <a href="[field:arcurl/]" class="item_link clearfix">
                  <div class="item_img"> <img src="[field:picname/]" alt="[field:title/]" />
                    <div class="item_mask"></div>
                  </div>
                  <div class="item_wrapper clearfix">
                    <div class="item_info clearfix">
                      <p class="nums ellipsis">0[field:global.autoindex/]</p>
                      <p class="title ellipsis">[field:title/]</p>
                      <p class="date_wrap"> <span class="year">[field:pubdate function="MyDate('Y',@me)"/]</span> <span class="md">[field:pubdate function="MyDate('m-d',@me)"/]</span> </p>
                      <div class="description">[field:description/]...</div>
                    </div>
                    <p class="details"><i class="fa fa-ico01" aria-hidden="true"></i></p>
                  </div>
                  </a>
                  <div class="o_ico"></div>
                  <div class="line"></div>
                  <div class="item_tags clearfix"> <a href="[field:typeurl/]">[field:typename/]</a> </div>
                </div>