<div id="item_block_[field:global.autoindex/]" class="item_block wow"> <a href="[field:arcurl/]" class="item_link clearfix" target="_blank">
                <div class="item_img"> <img src="[field:picname/]" alt="[field:title/] " />
                  <div class="item_mask"></div>
                </div>
                <div class="item_wrapper move">
                  <div class="item_info">
                    <p class="title ellipsis">[field:title/] </p>
                    <p class="subtitle ellipsis">[field:shorttitle/]</p>
                  </div>
                </div>
                </a> </div>