<div id="item_block_[field:global.autoindex/]" class="item_block wow"> <a href="view.php?aid=[field:id/]" class="item_link clearfix">
                        <div class="item_img"> <img src="[field:picname/]" alt="[field:title/]" />
                          <div class="item_mask"></div>
                        </div>
                        <div class="item_wrapper clearfix">
                          <p class="date_wrap"> <span class="year">[field:pubdate function="MyDate('Y',@me)"/]</span> <span class="md">[field:pubdate function="MyDate('m-d',@me)"/]</span> </p>
                          <div class="item_info clearfix">
                            <p class="title ellipsis">[field:title/]</p>
                            <div class="description">[field:description/]...</div>
                          </div>
                        </div>
                        </a>
                        <div class="o_ico"></div>
                        <div class="line"></div>
                      </div>