<div class="mcustomize module bgShow initlayout" style="background-image:url([field:typebg/]);   background-position: initial;background-size: cover;background-repeat: no-repeat; 
     background-size: initial; background-size: cover; background-attachment:fixed;  ">
      <div class="bgmask"></div>
      <div class="module_container">
        <div class="container_content">
          <div class="contentbody">
            <div class="wrapper">
              <div class="header wow">
                <p class="title">[field:typeeng/]</p>
                <p class="subtitle">[field:typename/]</p>
              </div>
              <div class="description wow">
                <p>[field:description/]...</p>
                <p><br />
                </p>
                <p><a href="[field:typelink/]" target="_blank" class="more">查看更多</a><br />
                </p>
              </div>
            </div>
          </div>
          <div class="clear"></div>
        </div>
      </div>
    </div>
	<!--工作方式-->
    <!--