<?php
$z[0]=Array("field","",311,340);
$z[0][4]=array();
$z[0][4]['name']="keywords";
$z[1]=Array("field","",379,438);
$z[1][4]=array();
$z[1][4]['name']="description";
$z[1][4]['function']="html2text(@me)";
$z[2]=Array("field","",1230,1249);
$z[2][4]=array();
$z[2][4]['name']="title";
$z[3]=Array("global","",1250,1276);
$z[3][4]=array();
$z[3][4]['name']="cfg_webname";
$z[4]=Array("list","\n              <div id=\"project_item_[field:global.autoindex/]\" class=\"item_block\" style=\"animation-delay:.[field:global.autoindex/]s\"> <a href=\"[field:video/]\" class=\"item_link clearfix\">\n                <div class=\"item_img\">\n                  <p class=\"img_box\"><img src=\"[field:picname/]\" alt=\"[field:title/]\" /></p>\n                  <div class=\"item_mask\"></div>\n                  <div class=\"item_ico\"></div>\n                </div>\n                <div class=\"item_wrapper clearfix\">\n                  <div class=\"item_info clearfix\">\n                    <p class=\"title ellipsis\">[field:title/]</p>\n                  </div>\n                </div>\n                </a> </div>\n              ",1991,2757);
$z[4][4]=array();
$z[4][4]['pagesize']="8";
$z[4][4]['addfields']="video";
$z[4][4]['channelid']="5";
$z[5]=Array("pagelist","",2928,2984);
$z[5][4]=array();
$z[5][4]['listitem']="pre,next,pageno";
$z[5][4]['listsize']="1";
$z[6]=Array("include","",3110,3149);
$z[6][4]=array();
$z[6][4]['filename']="footer_m.htm";
$z[7]=Array("type","list.php?tid=[field:id/]",3542,3600);
$z[7][4]=array();
$z[7][4]['typeid']="7";
$z[8]=Array("field","(@me==\"7\")? @me=\"active\":@me=\"\";",3609,3691);
$z[8][4]=array();
$z[8][4]['name']="typeid";
$z[8][4]['runphp']="yes";
$z[9]=Array("channel","\n        <li><a href=\"list.php?tid=[field:id/]\">[field:typename/]</a></li>\n        ",3717,3922);
$z[9][4]=array();
$z[9][4]['currentstyle']="<li><a href='~typelink~' class='active'>~typename~</a></li>";

?>