<?php
$z[0]=Array("field","",311,340);
$z[0][4]=array();
$z[0][4]['name']="keywords";
$z[1]=Array("field","",379,438);
$z[1][4]=array();
$z[1][4]['name']="description";
$z[1][4]['function']="html2text(@me)";
$z[2]=Array("field","",1230,1249);
$z[2][4]=array();
$z[2][4]['name']="title";
$z[3]=Array("global","",1250,1276);
$z[3][4]=array();
$z[3][4]['name']="cfg_webname";
$z[4]=Array("list","\n              <div id=\"item_block_[field:global.autoindex/]\" class=\"item_block wow\"> <a href=\"view.php?aid=[field:id/]\" class=\"item_link clearfix\">\n                <div href=\"view.php?aid=[field:id/]\" class=\"item_img\" target=\"_blank\">\n                  <p class=\"img_box\"><img src=\"[field:picname/]\" alt=\"[field:title/]\" /></p>\n                </div>\n                <div class=\"item_wrapper clearfix\">\n                  <div class=\"item_info clearfix\">\n                    <p class=\"title ellipsis\">[field:title/]</p>\n                    <div class=\"description\">\n                      <p>[field:description/]...</p>\n                    </div>\n                    <p class=\"details\"><i class=\"fa fa-ico01\" aria-hidden=\"true\"></i></p>\n                  </div>\n                </div>\n                </a> </div>\n              ",1980,2843);
$z[4][4]=array();
$z[4][4]['pagesize']="8";
$z[5]=Array("pagelist","",3014,3070);
$z[5][4]=array();
$z[5][4]['listitem']="pre,next,pageno";
$z[5][4]['listsize']="1";
$z[6]=Array("include","",3196,3235);
$z[6][4]=array();
$z[6][4]['filename']="footer_m.htm";

?>